### ISSUE TITLE
[suggestion] Automating installation

### ISSUE THREAD

**Issue by iambrj** [YoogottamK/dotfiles#5]
Looks like you don't have a script to automatically copy/link your dot files from your repo to appropriate locations, check [this](https://github.com/anishathalye/dotbot) out.

**Comment by yoogottamk** [comment]
Hello! Thanks a lot!

I will definitely work on an automated setup soon

**Comment by yoogottamk** [comment]
Thanks again!

ce1f7a49ec4e6dd038e5a8e43c4f4fd50faa64f3 adds this functionality
